const dataExpansion=["MEWTWO","CHARIZARD","PIKACHU","DIALGA","PALKIA","CELEBI"];
const dataCard={"172MEWTWO":{"expansion":"MEWTWO","type":"1 ROMBO","no":"172","name":"zubat"},"061CHARIZARD":{"expansion":"CHARIZARD","type":"3 ROMBOS","no":"061","name":"poliwarth"},"089CHARIZARD":{"expansion":"CHARIZARD","type":"3 ROMBOS","no":"089","name":"greninja"},"007PIKACHU":{"expansion":"PIKACHU","type":"3 ROMBOS","no":"007","name":"butterfree"},"040PIKACHU":{"expansion":"PIKACHU","type":"3 ROMBOS","no":"040","name":"arcanine"},"114PIKACHU":{"expansion":"PIKACHU","type":"3 ROMBOS","no":"114","name":"clefable"},"125PIKACHU":{"expansion":"PIKACHU","type":"3 ROMBOS","no":"125","name":"hypno"},"175MEWTWO":{"expansion":"MEWTWO","type":"3 ROMBOS","no":"175","name":"muk"},"056PIKACHU":{"expansion":"PIKACHU","type":"4 ROMBOS","no":"056","name":"blastoise ex"},"090DIALGA":{"expansion":"DIALGA","type":"1 ROMBO","no":"090","name":"wormadam"},"124PALKIA":{"expansion":"PALKIA","type":"1 ROMBO","no":"124","name":"Lickitung"},"005DIALGA":{"expansion":"DIALGA","type":"2 ROMBOS","no":"005","name":"Tangrowth"},"117DIALGA":{"expansion":"DIALGA","type":"2 ROMBOS","no":"117","name":"Bronzong"},"108DIALGA":{"expansion":"DIALGA","type":"2 ROMBOS","no":"108","name":"Toxicroak"},"074DIALGA":{"expansion":"DIALGA","type":"2 ROMBOS","no":"074","name":"Drifblim"},"152PALKIA":{"expansion":"PALKIA","type":"2 ROMBOS","no":"152","name":"cintia"},"150PALKIA":{"expansion":"PALKIA","type":"2 ROMBOS","no":"150","name":"Helio"},"028PALKIA":{"expansion":"PALKIA","type":"2 ROMBOS","no":"028","name":"monferno"},"089DIALGA":{"expansion":"DIALGA","type":"3 ROMBOS","no":"089","name":"Rampardos"},"020DIALGA":{"expansion":"DIALGA","type":"3 ROMBOS","no":"020","name":"leafeon"},"082PALKIA":{"expansion":"PALKIA","type":"3 ROMBOS","no":"082","name":"Rhyperior"},"114PALKIA":{"expansion":"PALKIA","type":"3 ROMBOS","no":"114","name":"Bastiodon"},"046PALKIA":{"expansion":"PALKIA","type":"3 ROMBOS","no":"046","name":"glaceon"},"024PALKIA":{"expansion":"PALKIA","type":"3 ROMBOS","no":"024","name":"Magmortar"},"079PALKIA":{"expansion":"PALKIA","type":"3 ROMBOS","no":"079","name":"Cresselia"},"129PALKIA":{"expansion":"PALKIA","type":"3 ROMBOS","no":"129","name":"Porygon-z"},"095DIALGA":{"expansion":"DIALGA","type":"4 ROMBOS","no":"095","name":"Gallade Ex"},"110DIALGA":{"expansion":"DIALGA","type":"4 ROMBOS","no":"110","name":"Darkrai ex"},"049PALKIA":{"expansion":"PALKIA","type":"4 ROMBOS","no":"049","name":"Palkia ex"},"067PALKIA":{"expansion":"PALKIA","type":"4 ROMBOS","no":"067","name":"Mismagius ex"}};
const dataType={"1 ROMBO":"0","2 ROMBOS":"0","3 ROMBOS":"120","4 ROMBOS":"500","1 ESTRELLA":"400"};

const keyExpansion=localStorage.hasOwnProperty("expansion");
const keyCard=localStorage.hasOwnProperty("card");
const keyType=localStorage.hasOwnProperty("type");


if(!keyExpansion)localStorage.setItem("expansion",JSON.stringify(dataExpansion))
if(!keyCard)localStorage.setItem("card",JSON.stringify(dataCard))
if(!keyType)localStorage.setItem("type",JSON.stringify(dataType))
